version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: geoint_postgres
    restart: always
    environment:
      POSTGRES_USER: geoint_user
      POSTGRES_PASSWORD: geoint_pass
      POSTGRES_DB: geoint_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: